### ISSUE TITLE
Add the name of the sender and the title of the video to the filename downloaded...

### ISSUE THREAD

**Issue by GitHubTW** [bagbag/mediathekviewweb#19]
... by using right mouse click on symbol 'floppy disk' and choosing 'save target as..'.

Is that possible?

THANKS!!!
Great website!!!

Best regards
Thomas

**Comment by bagbag** [comment]
The problem is, that the files are not served from my server, thats why I have limited control over it.

At the moment I'm using the [href download attribute](http://www.w3schools.com/tags/att_a_download.asp), but that's all I can do, at least using HTML. If you use "right click -> save as", I have even less control. And the download attribute even doesn't work for example in Chrome.

I know some Websites using JavaScript to download Files, but I didn't digged into that one any deeper yet. I will take a look at it soon , but can't promise anything.

**Comment by GitHubTW** [comment]
Thanks for your quick response and for this great website.
I am sure that someone who is able to implement such things is also able to solve this minor problem.
;-)

Best regards
Thomas

**Comment by bagbag** [comment]
The reason why the download attribute doesn't work: it's overwritten by "Content-Disposition" Header, which i cannot control.

I see only three possibilities:

1. use the server as a proxy to provide correct "Content-Disposition" Header
2. download the video into memory via XMLHttpRequest and then initiate a download of the blob
3. create a download client you run locally, which will be connected to your session (probably user) which will then perform the downloads.

1. it will introduce "huge" (network-)load to my server, which I will not (be able to) provide.
2. only works if ARD etc. have CORS enabled, which they (of course) have not.
3. should work always but requires by far the most work.

I think it's not worth all the work.
